[package]
name = "ppm"
version = "0.1.0"
authors = ["nzaouesgi <hakhenaton@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.0"

[lib]
name = "ppm_lib"
crate-type = ["dylib"]